#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : backcall
Version  : 0.2.0
Release  : 35
URL      : https://files.pythonhosted.org/packages/a2/40/764a663805d84deee23043e1426a9175567db89c8b3287b5c2ad9f71aa93/backcall-0.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a2/40/764a663805d84deee23043e1426a9175567db89c8b3287b5c2ad9f71aa93/backcall-0.2.0.tar.gz
Summary  : Specifications for callback functions passed in to an API
Group    : Development/Tools
License  : BSD-3-Clause
Requires: backcall-license = %{version}-%{release}
Requires: backcall-python = %{version}-%{release}
Requires: backcall-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
========
backcall
========
.. image:: https://travis-ci.org/takluyver/backcall.png?branch=master
:target: https://travis-ci.org/takluyver/backcall

%package license
Summary: license components for the backcall package.
Group: Default

%description license
license components for the backcall package.


%package python
Summary: python components for the backcall package.
Group: Default
Requires: backcall-python3 = %{version}-%{release}

%description python
python components for the backcall package.


%package python3
Summary: python3 components for the backcall package.
Group: Default
Requires: python3-core
Provides: pypi(backcall)

%description python3
python3 components for the backcall package.


%prep
%setup -q -n backcall-0.2.0
cd %{_builddir}/backcall-0.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635705994
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/backcall
cp %{_builddir}/backcall-0.2.0/LICENSE %{buildroot}/usr/share/package-licenses/backcall/ab5eb48d7d29fa62b23b1895d7e83f10144e54d7
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/backcall/ab5eb48d7d29fa62b23b1895d7e83f10144e54d7

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
