#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC518487173722F40 (takowl@gmail.com)
#
Name     : backcall
Version  : 0.1.0
Release  : 24
URL      : https://pypi.python.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
Source0  : https://pypi.python.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
Source1  : https://pypi.python.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz.asc
Summary  : Specifications for callback functions passed in to an API
Group    : Development/Tools
License  : BSD-3-Clause
Requires: backcall-python = %{version}-%{release}
Requires: backcall-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
backcall
        ========

%package python
Summary: python components for the backcall package.
Group: Default
Requires: backcall-python3 = %{version}-%{release}

%description python
python components for the backcall package.


%package python3
Summary: python3 components for the backcall package.
Group: Default
Requires: python3-core
Provides: pypi(backcall)

%description python3
python3 components for the backcall package.


%prep
%setup -q -n backcall-0.1.0
cd %{_builddir}/backcall-0.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1602133193
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
